services:
  - type: web
    name: stock-index-api
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: A股指数分析系统
      - key: APP_VERSION
        value: 1.0.0
      - key: DEBUG
        value: False
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: sqlite:///./data/stock_index.db
      - key: REDIS_HOST
        value: localhost
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_DB
        value: 0
      - key: DATA_SOURCE
        value: akshare
      - key: DATA_UPDATE_INTERVAL
        value: 5
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FILE
        value: ./logs/app.log
